/RMG/Manager/Logging/LogLevel detail

/RMG/Geometry/RegisterDetector Germanium V00048A 001
/RMG/Geometry/RegisterDetector Germanium V01240A 002

/RMG/Output/ActivateOutputScheme ParticleFilter

/run/initialize

/RMG/Output/ParticleFilter/AddParticle -12 
/RMG/Output/ParticleFilter/AddParticle  12 

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Physical/AddVolume Source

/RMG/Generator/Select GPS
/gps/particle ion
/gps/ion 90 228 # Thorium-228
#/gps/ion 56 133 # Barium-133
#/gps/ion 95 241 # Americium-241
/gps/ang/type iso

/run/beamOn 53000
